### ISSUE TITLE
WHy nO tESTS‽ 

### ISSUE THREAD

**Issue by coryodaniel** [supersimple/spongebob#1]
HAvE yoU EveN heaRD Of TDd‽

**Comment by supersimple** [comment]
tests are for simps

**Comment by coryodaniel** [comment]
I found a bug see screenshot: https://gist.github.com/coryodaniel/212c1a684882cfbee54870470d61a638

**Comment by supersimple** [comment]
thanks for the bug report!
I am not sure how to fix it, so I am going to forward it to @yourmom

**Comment by supersimple** [comment]
![image](https://user-images.githubusercontent.com/773380/127595139-e08f1af1-a19f-4122-b358-d8aeb4f5ce39.png)
